$bg = rgba(201515ff)
$fg = rgba(d6b3b3ff)
$black = rgba(201515ff)
$red = rgba(ff5555ff)
$green = rgba(9ece6aff)
$yellow = rgba(e0af68ff)
$blue = rgba(7aa2f7ff)
$magenta = rgba(ad8ee6ff)
$cyan = rgba(449dabff)
$white = rgba(d0b8b8ff)

$transparent = rgba(00000000)
$accent = $red
