-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local bg = "rgba(201515ff)"
local fg = "rgba(d6b3b3ff)"
local black = "rgba(201515ff)"
local red = "rgba(ff5555ff)"
local green = "rgba(9ece6aff)"
local yellow = "rgba(e0af68ff)"
local blue = "rgba(7aa2f7ff)"
local magenta = "rgba(ad8ee6ff)"
local cyan = "rgba(449dabff)"
local white = "rgba(d0b8b8ff)"

local transparent = "rgba(00000000)"
local accent = red

return {
    bg = bg,
    fg = fg,
    black = black,
    red = red,
    green = green,
    yellow = yellow,
    blue = blue,
    magenta = magenta,
    cyan = cyan,
    white = white,
    transparent = transparent,
    accent = accent,
}
