-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local hypr = "~/.config/hypr"
local conf = hypr .. "/conf"
local theme = "tokyonight"

-- Source: $conf/env_vars.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_conf.env_vars")
-- Source: $conf/env_vars_nvidia.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_conf.env_vars_nvidia")

-- Source: $hypr/themes/$theme.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_hypr.themes._theme")
-- Source: $conf/startup.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_conf.startup")

-- Source: $conf/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_conf.monitors")
-- Source: $conf/binds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_conf.binds")
-- Source: $conf/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_conf.input")

-- Source: $conf/layouts.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_conf.layouts")
-- Source: $conf/rules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_conf.rules")
-- Source: $conf/decoration.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_conf.decoration")

-- source = $conf/plugin.conf
hl.config({
    input = {
        kb_layout = "fr",
    },
})
