-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local scripts = "~/scripts"
local launch = "~/scripts/launch.fish"

-- Source: $conf/defaults.conf — convert this file to Lua and ensure it is on Lua's package.path.
local D = require("conf.defaults")

-- ── Apps ────────────────────────────────────────────────────────────
hl.bind("SUPER + return", hl.dsp.exec_cmd(D.terminal))
hl.bind("SUPER + CTRL + return", hl.dsp.exec_cmd(D.terminal2))
hl.bind("SUPER + T", hl.dsp.exec_cmd(launch .. " tmux"))
hl.bind("SUPER + b", hl.dsp.exec_cmd("[workspace 2 ] " .. launch .. " firefox"))
hl.bind("SUPER + e", hl.dsp.exec_cmd(D.files))
hl.bind("SUPER + R", hl.dsp.exec_cmd("fuzzel"))
-- bind = SUPER,       D,      exec,         $dmenu
-- bind = SUPER SHIFT, D,      exec,         makoctl dismiss -a
hl.bind("SUPER + N", hl.dsp.exec_cmd("swaync-client -t"))
hl.bind("XF86Calculator", hl.dsp.exec_cmd("/usr/sbin/gnome-calculator"))

-- ── Ags ─────────────────────────────────────────────────────────────
-- bind = SUPER CTRL,  A,      exec,         $powermenu
-- bind = SUPER CTRL,  S,      exec,         $quicksettings
-- bind = SUPER CTRL,  D,      exec,         $dashboard
-- bind = SUPER CTRL,  O,      exec,         $overview

-- ── Utils ───────────────────────────────────────────────────────────
hl.bind("SUPER + SHIFT + equal", hl.dsp.exec_cmd(D.colorPicker))
hl.bind("SUPER + V", hl.dsp.exec_cmd(D.clipboard))
hl.bind("print", hl.dsp.exec_cmd("hyprshot -m output"))
hl.bind("CTRL + print", hl.dsp.exec_cmd("hyprshot -m region"))
hl.bind("SHIFT + print", hl.dsp.exec_cmd("hyprshot -m window"))
hl.bind("SUPER + x", hl.dsp.exec_cmd("wl-kbptr"))

-- ── Session ──────────────────────────────────────────────────────────
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + SHIFT + Q", hl.dsp.exec_cmd(scripts .. "/wlogout.sh"))
hl.bind("SUPER + ALT + Q", hl.dsp.exit())
hl.bind("SUPER + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind("SUPER + SHIFT + escape", hl.dsp.exec_cmd("hyprlock"))
hl.bind("SUPER + SHIFT + B", hl.dsp.exec_cmd("killall -SIGUSR1 waybar"))

--         ╭───────────────────────────────────────────────────────────╮
--         │                          Window                           │
--         ╰───────────────────────────────────────────────────────────╯

-- ── Window ──────────────────────────────────────────────────────────
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind("SUPER + SHIFT + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + CTRL + F", hl.dsp.window.center())
hl.bind("SUPER + ALT + TAB", hl.dsp.layout("swapwithmaster master, "))

-- ── Focus ───────────────────────────────────────────────────────────
hl.bind("SUPER + left", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + right", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + up", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + down", hl.dsp.focus({ direction = "down" }))
hl.bind("SUPER + h", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + l", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + k", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + j", hl.dsp.focus({ direction = "down" }))

-- ── Move ────────────────────────────────────────────────────────────
hl.bind("SUPER + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER + SHIFT + down", hl.dsp.window.move({ direction = "d" }))
hl.bind("SUPER + SHIFT + h", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER + SHIFT + l", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER + SHIFT + k", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER + SHIFT + j", hl.dsp.window.move({ direction = "d" }))

-- ── Reize ───────────────────────────────────────────────────────────
hl.bind("SUPER + CTRL + right", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
hl.bind("SUPER + CTRL + left", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
hl.bind("SUPER + CTRL + up", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
hl.bind("SUPER + CTRL + down", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })
hl.bind("SUPER + CTRL + l", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
hl.bind("SUPER + CTRL + h", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
hl.bind("SUPER + CTRL + k", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
hl.bind("SUPER + CTRL + j", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })

--         ╭───────────────────────────────────────────────────────────╮
--         │                         Workspace                         │
--         ╰───────────────────────────────────────────────────────────╯

-- ── Switch ──────────────────────────────────────────────────────────
-- bind = SUPER,       1,            workspace,                      1
-- bind = SUPER,       2,            workspace,                      2
-- bind = SUPER,       3,            workspace,                      3
-- bind = SUPER,       4,            workspace,                      4
-- bind = SUPER,       5,            workspace,                      5
-- bind = SUPER,       6,            workspace,                      6
-- bind = SUPER,       7,            workspace,                      7
-- bind = SUPER,       8,            workspace,                      8
-- bind = SUPER,       9,            workspace,                      9
-- bind = SUPER,       0,            workspace,                      10

-- ── Switch on Focused Monitor ────────────────────────────────────────
hl.bind("SUPER + ampersand", hl.dsp.focus({ workspace = 1, on_current_monitor = true }))
hl.bind("SUPER + eacute", hl.dsp.focus({ workspace = 2, on_current_monitor = true }))
hl.bind("SUPER + quotedbl", hl.dsp.focus({ workspace = 3, on_current_monitor = true }))
hl.bind("SUPER + apostrophe", hl.dsp.focus({ workspace = 4, on_current_monitor = true }))
hl.bind("SUPER + parenleft", hl.dsp.focus({ workspace = 5, on_current_monitor = true }))
hl.bind("SUPER + minus", hl.dsp.focus({ workspace = 6, on_current_monitor = true }))
-- bind = SUPER CTRL,  7,            focusworkspaceoncurrentmonitor, 7
-- bind = SUPER CTRL,  8,            focusworkspaceoncurrentmonitor, 8
-- bind = SUPER CTRL,  9,            focusworkspaceoncurrentmonitor, 9
-- bind = SUPER CTRL,  0,            focusworkspaceoncurrentmonitor, 10

-- ── Move + Focus ────────────────────────────────────────────────────
hl.bind("SUPER + SHIFT + ampersand", hl.dsp.window.move({ workspace = 1 }))
hl.bind("SUPER + SHIFT + eacute", hl.dsp.window.move({ workspace = 2 }))
hl.bind("SUPER + SHIFT + quotedbl", hl.dsp.window.move({ workspace = 3 }))
hl.bind("SUPER + SHIFT + apostrophe", hl.dsp.window.move({ workspace = 4 }))
hl.bind("SUPER + SHIFT + parenleft", hl.dsp.window.move({ workspace = 5 }))
hl.bind("SUPER + SHIFT + minus", hl.dsp.window.move({ workspace = 6 }))
-- bind = SUPER SHIFT, 7,            movetoworkspace,                7
-- bind = SUPER SHIFT, 8,            movetoworkspace,                8
-- bind = SUPER SHIFT, 9,            movetoworkspace,                9
-- bind = SUPER SHIFT, 0,            movetoworkspace,                10

-- ── Move Silent ─────────────────────────────────────────────────────
hl.bind("SUPER + ALT + ampersand", hl.dsp.window.move({ workspace = 1, follow = false }))
hl.bind("SUPER + ALT + eacute", hl.dsp.window.move({ workspace = 2, follow = false }))
hl.bind("SUPER + ALT + quotedbl", hl.dsp.window.move({ workspace = 3, follow = false }))
hl.bind("SUPER + ALT + apostrophe", hl.dsp.window.move({ workspace = 4, follow = false }))
hl.bind("SUPER + ALT + parenleft", hl.dsp.window.move({ workspace = 5, follow = false }))
hl.bind("SUPER + ALT + minus", hl.dsp.window.move({ workspace = 6, follow = false }))
-- bind = SUPER ALT,   7,            movetoworkspacesilent,          7
-- bind = SUPER ALT,   8,            movetoworkspacesilent,          8
-- bind = SUPER ALT,   9,            movetoworkspacesilent,          9
-- bind = SUPER ALT,   0,            movetoworkspacesilent,          10

-- ── Scratchpad ──────────────────────────────────────────────────────
hl.bind("SUPER + D", hl.dsp.workspace.toggle_special(""))
hl.bind("SUPER + SHIFT + D", hl.dsp.window.move({ workspace = "special" }))
hl.bind("SUPER + ALT + D", hl.dsp.window.move({ workspace = "special", follow = false }))

hl.bind("SUPER + U", hl.dsp.workspace.toggle_special("secondary"))
hl.bind("SUPER + SHIFT + U", hl.dsp.window.move({ workspace = "special:secondary" }))
hl.bind("SUPER + ALT + U", hl.dsp.window.move({ workspace = "special:secondary", follow = false }))

hl.bind("SUPER + I", hl.dsp.workspace.toggle_special("third"))
hl.bind("SUPER + SHIFT + I", hl.dsp.window.move({ workspace = "special:third" }))
hl.bind("SUPER + ALT + I", hl.dsp.window.move({ workspace = "special:third", follow = false }))

-- ── Monitors ────────────────────────────────────────────────────────
hl.bind("SUPER + S", hl.dsp.focus({ monitor = "+1" }))
-- bind = SUPER,       BracketRight, focusmonitor,                   -1
-- bind = SUPER,       BracketLeft,  focusmonitor,                   +1
hl.bind("SUPER + SHIFT + M",
    function()
        local w = hl.get_active_workspace(); if not w then return end; hl.dispatch(hl.dsp.workspace.move({
            workspace = w
                .id,
            monitor = "+1"
        }))
    end)
hl.bind("SUPER + SHIFT + BracketRight",
    function()
        local w = hl.get_active_workspace(); if not w then return end; hl.dispatch(hl.dsp.workspace.move({
            workspace = w
                .id,
            monitor = -1
        }))
    end)
hl.bind("SUPER + SHIFT + BracketLeft",
    function()
        local w = hl.get_active_workspace(); if not w then return end; hl.dispatch(hl.dsp.workspace.move({
            workspace = w
                .id,
            monitor = "+1"
        }))
    end)
hl.bind("SUPER + CTRL + Tab", hl.dsp.workspace.swap_monitors({ monitor1 = "0", monitor2 = "1" }))

-- ── Move/resize windows with the mouse ──────────────────────────────
hl.bind("SUPER + mouse:272", hl.dsp.window.drag())
hl.bind("SUPER + mouse:273", hl.dsp.window.resize())

--         ╭───────────────────────────────────────────────────────────╮
--         │                        Media Binds                        │
--         ╰───────────────────────────────────────────────────────────╯

hl.bind("xf86audioraisevolume", hl.dsp.exec_cmd(scripts .. "/volume.fish inc"))
hl.bind("xf86audiolowervolume", hl.dsp.exec_cmd(scripts .. "/volume.fish dec"))
hl.bind("xf86AudioMicMute", hl.dsp.exec_cmd(scripts .. "/volume.fish --toggle-mic"))
hl.bind("xf86audioMute", hl.dsp.exec_cmd(scripts .. "/volume.fish mute"))

hl.bind("xf86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("xf86AudioNext", hl.dsp.exec_cmd("playerctl next"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

-- bind =,          xf86KbdBrightnessDown, exec, $scripts/kb-brightness --dec
-- bind =,          xf86KbdBrightnessUp,   exec, $scripts/kb-brightness --inc

hl.bind("xf86MonBrightnessDown", hl.dsp.exec_cmd(scripts .. "/brightness --dec"))
hl.bind("xf86MonBrightnessUp", hl.dsp.exec_cmd(scripts .. "/brightness --inc"))

hl.bind("SUPER + ALT + minus", hl.dsp.exec_cmd(scripts .. "/brightness --dec"))
hl.bind("SUPER + ALT + equal", hl.dsp.exec_cmd(scripts .. "/brightness --inc"))

-- bind =,          122,                   exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
-- bind =,          123,                   exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
-- bind =,          121,                   exec, pactl set-sink-volume @DEFAULT_SINK@ 0%

hl.bind("CTRL + xf86audioraisevolume", hl.dsp.exec_cmd("playerctl next"))
hl.bind("CTRL + xf86audiolowervolume", hl.dsp.exec_cmd("playerctl previous"))
hl.bind("CTRL + xf86audioMute", hl.dsp.exec_cmd("playerctl play-pause"))

-- 60% Keyboard
hl.bind("SUPER + equal", hl.dsp.exec_cmd(scripts .. "/volume.fish inc"))
hl.bind("SUPER + minus", hl.dsp.exec_cmd(scripts .. "/volume.fish dec"))
hl.bind("SUPER + 0", hl.dsp.exec_cmd(scripts .. "/volume.fish mute"))
hl.bind("SUPER + comma", hl.dsp.exec_cmd("playerctl previous"))
hl.bind("SUPER + p", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("SUPER + period", hl.dsp.exec_cmd("playerctl next"))

--         ╭───────────────────────────────────────────────────────────╮
--         │                          Submaps                          │
--         ╰───────────────────────────────────────────────────────────╯

-- ── Launch ──────────────────────────────────────────────────────────
hl.bind("SUPER + Space", hl.dsp.exec_cmd(launch .. " hypr_launch"))
hl.bind("SUPER + Space", hl.dsp.submap("launch"))
hl.define_submap("launch", function()
    hl.bind("w", hl.dsp.exec_cmd("wezterm"), { repeating = true })
    hl.bind("w", hl.dsp.exec_cmd(launch .. " hypr_reset"))
    hl.bind("w", hl.dsp.submap("reset"))

    hl.bind("r", hl.dsp.exec_cmd(scripts .. "/rofi_select.sh"), { repeating = true })
    hl.bind("r", hl.dsp.exec_cmd(launch .. " hypr_reset"), { repeating = true })
    hl.bind("r", hl.dsp.submap("reset"))

    hl.bind("t", hl.dsp.exec_cmd(scripts .. "/rofi_tmux.sh"), { repeating = true })
    hl.bind("t", hl.dsp.exec_cmd(launch .. " hypr_reset"), { repeating = true })
    hl.bind("t", hl.dsp.submap("reset"))

    hl.bind("SHIFT + t", hl.dsp.exec_cmd("lxtask"), { repeating = true })
    hl.bind("SHIFT + t", hl.dsp.exec_cmd(launch .. " hypr_reset"), { repeating = true })
    hl.bind("SHIFT + t", hl.dsp.submap("reset"))

    hl.bind("u", hl.dsp.exec_cmd(scripts .. "/pick_theme.sh"), { repeating = true })
    hl.bind("u", hl.dsp.exec_cmd(launch .. " hypr_reset"), { repeating = true })
    hl.bind("u", hl.dsp.submap("reset"))

    hl.bind("i", hl.dsp.exec_cmd("makoctl dismiss"), { repeating = true })
    hl.bind("i", hl.dsp.exec_cmd(launch .. " hypr_reset"), { repeating = true })
    hl.bind("i", hl.dsp.submap("reset"))

    hl.bind("p", hl.dsp.exec_cmd(scripts .. "/project.sh rofi"), { repeating = true })
    hl.bind("p", hl.dsp.exec_cmd(launch .. " hypr_reset"), { repeating = true })
    hl.bind("p", hl.dsp.submap("reset"))

    hl.bind("a", hl.dsp.exec_cmd("kitty"), { repeating = true })
    hl.bind("a", hl.dsp.exec_cmd(launch .. " hypr_reset"), { repeating = true })
    hl.bind("a", hl.dsp.submap("reset"))

    hl.bind("s", hl.dsp.exec_cmd("[workspace 5 silent] " .. D.spotify), { repeating = true })
    hl.bind("s", hl.dsp.exec_cmd(launch .. " hypr_reset"), { repeating = true })
    hl.bind("s", hl.dsp.submap("reset"))

    hl.bind("SHIFT + s", hl.dsp.exec_cmd(launch .. " spt"), { repeating = true })
    hl.bind("SHIFT + s", hl.dsp.exec_cmd(launch .. " hypr_reset"), { repeating = true })
    hl.bind("SHIFT + s", hl.dsp.submap("reset"))

    hl.bind("d", hl.dsp.exec_cmd("[workspace 5 silent] webcord"), { repeating = true })
    hl.bind("d", hl.dsp.exec_cmd(launch .. " hypr_reset"), { repeating = true })
    hl.bind("d", hl.dsp.submap("reset"))

    hl.bind("g", hl.dsp.exec_cmd(scripts .. "/open_repo.fish"), { repeating = true })
    hl.bind("g", hl.dsp.exec_cmd(launch .. " hypr_reset"), { repeating = true })
    hl.bind("g", hl.dsp.submap("reset"))

    hl.bind("h", hl.dsp.exec_cmd(D.httpclient), { repeating = true })
    hl.bind("h", hl.dsp.exec_cmd(launch .. " hypr_reset"), { repeating = true })
    hl.bind("h", hl.dsp.submap("reset"))

    hl.bind("k", hl.dsp.exec_cmd("kitty"), { repeating = true })
    hl.bind("k", hl.dsp.exec_cmd(launch .. " hypr_reset"), { repeating = true })
    hl.bind("k", hl.dsp.submap("reset"))

    --binde=,        l,         exec,         $launch lunarvide
    --binde=,        l,         exec,         $launch hypr_reset
    --binde=,        l,         submap,       reset

    hl.bind("c", hl.dsp.exec_cmd(D.code), { repeating = true })
    hl.bind("c", hl.dsp.exec_cmd(launch .. " hypr_reset"), { repeating = true })
    hl.bind("c", hl.dsp.submap("reset"))

    hl.bind("b", hl.dsp.exec_cmd(launch .. " passwords"), { repeating = true })
    hl.bind("b", hl.dsp.exec_cmd(launch .. " hypr_reset"), { repeating = true })
    hl.bind("b", hl.dsp.submap("reset"))

    hl.bind("n", hl.dsp.exec_cmd(D.neovide), { repeating = true })
    hl.bind("n", hl.dsp.exec_cmd(launch .. " hypr_reset"), { repeating = true })
    hl.bind("n", hl.dsp.submap("reset"), { repeating = true })

    hl.bind("q", hl.dsp.submap("reset"))

    hl.bind("escape", hl.dsp.exec_cmd(launch .. " hypr_reset"), { repeating = true })
    hl.bind("escape", hl.dsp.submap("reset"))
end)

-- ── Window Mode ─────────────────────────────────────────────────────
hl.bind("SUPER + w", hl.dsp.exec_cmd(launch .. " hypr_windowmode"))
hl.bind("SUPER + w", hl.dsp.submap("WindowMode"))
hl.define_submap("WindowMode", function()
    hl.bind("left", hl.dsp.focus({ direction = "left" }))
    hl.bind("right", hl.dsp.focus({ direction = "right" }))
    hl.bind("up", hl.dsp.focus({ direction = "up" }))
    hl.bind("down", hl.dsp.focus({ direction = "down" }))
    hl.bind("h", hl.dsp.focus({ direction = "left" }))
    hl.bind("l", hl.dsp.focus({ direction = "right" }))
    hl.bind("k", hl.dsp.focus({ direction = "up" }))
    hl.bind("j", hl.dsp.focus({ direction = "down" }))

    hl.bind("SHIFT + left", hl.dsp.window.move({ direction = "l" }))
    hl.bind("SHIFT + right", hl.dsp.window.move({ direction = "r" }))
    hl.bind("SHIFT + up", hl.dsp.window.move({ direction = "u" }))
    hl.bind("SHIFT + down", hl.dsp.window.move({ direction = "d" }))
    hl.bind("SHIFT + h", hl.dsp.window.move({ direction = "l" }))
    hl.bind("SHIFT + l", hl.dsp.window.move({ direction = "r" }))
    hl.bind("SHIFT + k", hl.dsp.window.move({ direction = "u" }))
    hl.bind("SHIFT + j", hl.dsp.window.move({ direction = "d" }))

    hl.bind("CTRL + right", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
    hl.bind("CTRL + left", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
    hl.bind("CTRL + up", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
    hl.bind("CTRL + down", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })
    hl.bind("CTRL + l", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
    hl.bind("CTRL + h", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
    hl.bind("CTRL + k", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
    hl.bind("CTRL + j", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })

    hl.bind("mouse:272", hl.dsp.window.drag())
    hl.bind("mouse:273", hl.dsp.window.resize())

    hl.bind("escape", hl.dsp.exec_cmd(launch .. " hypr_reset"), { repeating = true })
    hl.bind("escape", hl.dsp.submap("reset"))
end)
