-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
local theme = require("themes.tokyonight")

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.curve("bezier2", { type = "bezier", points = { { 0.5, 0.1 }, { 0.5, 0.9 } } })
hl.curve("border", { type = "bezier", points = { { 0.2, 0.3 }, { 0.8, 0.7 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 7,
    bezier = "myBezier",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 6,
    bezier = "default",
    style = "popin 90%",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 10,
    bezier = "border",
    style = "loop",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 7,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 5,
    bezier = "default",
})
hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 3,
    bezier = "myBezier",
    style = "slidevert",
})
hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 4,
        border_size = 1,
        col = {
            active_border = theme.accent,
            inactive_border = theme.transparent,
        },
    },
    decoration = {
        rounding = 8,
        blur = {
            enabled = true,
            size = 2,
            passes = 4,
            new_optimizations = true,
            ignore_opacity = true,
            xray = false,
            noise = 0.06,
            brightness = 0.7,
        },
        dim_inactive = false,
        dim_strength = 0.1,
        dim_special = 0.4,
        dim_around = 0.4,
        inactive_opacity = 0.95,
    },
    animations = {
        enabled = true,
    },
})
