-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local scripts = "~/scripts"
local launch = "~/scripts/launch.fish"
local modules = "~/.config/hypr/modules"
local alacritty = "alacritty"
local rofi_config = "rofi -config ~/.config/rofi/config.rasi"

-- $terminal = $alacritty
local terminal = alacritty
local terminal2 = alacritty
local editor = "zed"
local files = "thunar"
local code = "/usr/bin/code --password-store=\"gnome\""
local rofi = rofi_config .. " -show drun -show-icons"
local dmenu = "bemenu-run"
local tmux = launch .. " tmux"
local nvim = alacritty .. " --hold -e nvim &"
local neovide = "neovide"
local filestui = alacritty .. " -e yazi"
local clipboard = "cliphist list | " .. rofi_config .. " -dmenu | cliphist decode | wl-copy"
local spotify = "spotify-launcher"
local httpclient = "postman"

local colorPicker = "hyprpicker -a"

local powermenu = "ags -t powermenu"
local quicksettings = "ags -t quicksettings"
local overview = "ags -t overview"
local dashboard = "ags -t dashboard"
