-- ============================================
-- Mirrored setup (commented out)
-- ============================================
-- monitor=eDP-1, 1920x1080@60, 0x0, 1
-- monitor=HDMI-A-1, 1920x1080@60, 0x0, 1, mirror, eDP-1

-- ============================================
-- Dual monitor setup - Extended desktop
-- ============================================
-- HDMI-A-1 (ASUS VA279HG) - Main monitor on the LEFT at 120Hz
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60",
    position = "0x0",
    scale = "1",
})

-- eDP-1 (LG Laptop Display) - Secondary monitor on the RIGHT at 120Hz
hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60",
    position = "1920x0",
    scale = "1",
})
