-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.layer_rule({ match = { namespace = "waybar" }, blur = true })
hl.layer_rule({ match = { namespace = "overlay" }, blur = true })
hl.layer_rule({ match = { namespace = "gtk-layer-shell" }, blur = true })
hl.layer_rule({ match = { namespace = "rofi" }, blur = true })
hl.layer_rule({ match = { namespace = "mako" }, blur = true })

hl.window_rule({
    match = {
        class = "^(pavucontrol)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(blueman-manager)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(nm-connection-editor)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Picture-in-Picture)$",
    },
    size = "960 540",
    move = "25% 75%",
})

hl.window_rule({
    match = {
        class = "^(firefox)$",
    },
    no_blur = true,
})

hl.window_rule({
    match = {
        class = "^(thunar)$",
    },
    opacity = "0.8 0.8",
})

hl.window_rule({
    match = {
        class = "^(Spotify)$",
    },
    opacity = "0.8 0.8",
})

hl.window_rule({
    match = {
        class = "^(WebCord)$",
    },
    opacity = "0.8 0.8",
})

hl.window_rule({
    match = {
        class = "^(Code)$",
    },
    opacity = "0.9 0.9",
})

hl.window_rule({
    match = {
        class = "^(mako)$",
    },
    opacity = "0.9 0.9",
})

hl.window_rule({
    match = {
        float = true,
    },
    opacity = "0.7 0.7",
})

hl.window_rule({
    match = {
        class = "^()$",
        title = "^(Picture in picture)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(xdg-desktop-portal-gtk)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(xdg-desktop-portal-kde)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(xdg-desktop-portal-hyprland)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(submap)$",
    },
    float = true,
    center = true,
})

hl.window_rule({
    match = {
        title = "^(Developer Tools.*)$",
    },
    float = false,
})
