-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

--exec-once = copyq

--exec-once = megasync

hl.on("hyprland.start", function()
    hl.exec_cmd("~/.config/hypr/xdg-portal-hyprland")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("sleep 1 && awww img ~/.config/hypr/wallpapers/tokyonight.jpg --transition-type grow")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("~/.config/waybar/launch_preferred_output.sh")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("exec xrdb -load ~/.Xresources")
    hl.exec_cmd("wl-paste -t text --watch clipman store")
    hl.exec_cmd("wl-clipboard-history -t")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("sh ~/.config/hypr/conf/startup.sh")
end)

hl.on("config.reloaded", function()
    hl.exec_cmd("hyprctl notify -1 3000 \"rgb(7aa2f7)\" \"Startup Finished :)\"")
end)
