#!/usr/bin/env bash

# Get brightness
get_backlight() {
	LIGHT=$(printf "%.0f\n" $(brightnessctl i))
	echo "${LIGHT}%"
}

# Notify
notify_user() {
	# notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Brightness : $(brightnessctl g)"
percentage=$(expr $(brightnessctl g) \* 100 / $(brightnessctl m))
hyprctl notify -1 1000 "rgb(31748F)" $percentage
}

# Increase brightness
inc_backlight() {
	brightnessctl set 5%+ && notify_user
}

# Decrease brightness
dec_backlight() {
	brightnessctl set 5%- && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	brightnessctl g
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
